### ISSUE TITLE
Support for SQL query and/or LOV for tag display/return values

### ISSUE THREAD

**Issue by mortenbra** [rodrigomesquitaorclapex/apex-Multi-Select-TAG#1]
Nice plugin, but it should support an SQL query and/or a predefined LOV as the source for the tag display/return values.
Could be implemented via the apex_plugin_util.get_data function, see https://docs.oracle.com/cd/E59726_01/doc.50/e39149/apex_plugin_util.htm#AEAPI2163

**Comment by rodrigomesquitaorclapex** [comment]
sure! thanks, im working on it for the next version
